#!/bin/bash
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
# 
#   http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations

platform='unknown'
unamestr=`uname`
if [[ "$unamestr" == 'Linux' ]]; then
   platform='linux'
elif [[ "$unamestr" == 'FreeBSD' ]]; then
   platform='freebsd'
 elif [[ "$unamestr" == 'Darwin' ]]; then
    platform='osx'   
fi

if [[ $platform == 'osx' ]]; then
  docker rm -f systemml
  docker run -d --name systemml -p 7077:7077 -p 8080:8080 -p 8081:8081  -p 8085:8085 -p 8086:8086 -p 8087:8087 -p 8088:8088 -p 50070:50070 -p 6500:6500 -p 6501:6501 -p 6502:6502 -p 18080:18080 lresende/systemml
  
  DOCKER_IP="$(docker exec systemml /bin/hostname -i)"
  VM_IP="$(docker-machine ip default)"
else
  sudo docker rm -f systemml
  sudo docker run -d --name systemml -p 7077:7077 -p 8080:8080 -p 8081:8081 -p 8085:8085 -p 8086:8086 -p 8087:8087 -p 8088:8088 -p 50070:50070 -p 6500:6500 -p 6501:6501 -p 6502:6502 -p 18080:18080 lresende/systemml

  DOCKER_IP="$(sudo docker exec systemml /bin/hostname -i)"
  VM_IP="$(docker-machine ip default)"
fi

echo " "
echo "Zepplin UI    http://$VM_IP:8081"
echo "Spark Console http://$VM_IP:8080"
echo "Yarn  Console http://$VM_IP:8088"
echo "HDFS  Console http://$VM_IP:50070"
echo "Use spark-submit $VM_IP"
